# Site settings
name: Afshin Shahrestani
title: Afshin Shahrestani | Computer Science Student
description: Computer Science Student focused on advancing Machine Learning and Data Mining and connecting them to everyday problems 
url: https://ashthefallen.github.io/
baseurl: ''
email: ash.shahrestani@gmail.com
cover: https://ashthefallen.github.io/img/og.png
logo: https://ashthefallen.github.io/img/emojis/alienmonster.png
resume: https://ashthefallen.github.io/resume.pdf
social:
  - title: email
    url: mailto:ash.shahrestani@gmail.com
  - title: twitter
    url: https://twitter.com/FromAsh2Dust
  # - title: instagram
  #   url: https://instagram.com/bchiang7
  # - title: codepen
  #   url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/ashthefallen
  - title: linkedin
    url: https://www.linkedin.com/in/afshin-shahrestani/
  - title: scholar
    url: https://scholar.google.com/citations?user=cDgIzQMAAAAJ&hl=en  

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
